import { test, expect } from '@playwright/test'
import Database from 'better-sqlite3'

test('图形编辑：只读发布包、节点与JSON同步、未保存保护、审核发布并保留旧局', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/account')
  await page.getByLabel('用户名', { exact: true }).fill(`graph_${Date.now()}`)
  await page.getByLabel('密码', { exact: true }).fill('story-graph-testing-passphrase')
  await page.getByRole('button', { name: '创建我的空间' }).click()
  await expect(page.getByRole('heading', { name: '请妥善保存一次性恢复码' })).toBeVisible()
  await page.getByRole('button', { name: '我已保存，隐藏恢复码' }).click()
  const identity = await (await page.request.get('/api/me')).json()
  const database = new Database(process.env.E2E_DATABASE_PATH!)
  try {
    for (const role of ['editor', 'reviewer', 'admin'])
      database.prepare('INSERT OR IGNORE INTO user_roles VALUES (?,?)').run(identity.user.id, role)
  } finally {
    database.close()
  }
  await page.goto('/')
  await page.getByRole('button', { name: '开启第一段职境' }).click()
  await expect(page.locator('.save-status')).toContainText('已保存')
  const oldSessionPath = new URL(page.url()).pathname
  const oldSession = await (
    await page.request.get(`/api/sessions/${oldSessionPath.split('/').at(-1)}`)
  ).json()
  await page.goto('/admin')
  await expect(page.getByTestId('content-graph-editor')).toBeVisible()
  await expect(page.getByTestId('apply-node')).toBeDisabled()
  await page.getByRole('button', { name: '复制为草稿', exact: true }).click()
  await expect(page.locator('.admin-list button[aria-pressed=true]')).toContainText('draft')
  await page.getByTestId('node-title').fill('图形编辑：先认识这个工作日')
  await page.getByTestId('story-node-briefing').click()
  await expect(page.getByTestId('node-switch-warning')).toBeVisible()
  await page.getByRole('button', { name: '继续编辑当前节点' }).click()
  await expect(page.getByTestId('node-title')).toHaveValue('图形编辑：先认识这个工作日')
  await page.getByRole('button', { name: '保存草稿', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('请先应用或撤销')
  page.once('dialog', (dialog) => dialog.dismiss())
  await page.locator('.admin-list button').filter({ hasText: 'v2 ·' }).click()
  await expect(page.getByTestId('node-title')).toHaveValue('图形编辑：先认识这个工作日')
  await page.getByTestId('apply-node').click()
  await page.getByRole('tab', { name: '高级 JSON' }).click()
  const packText = await page.getByLabel('内容包 JSON 编辑器').inputValue()
  expect(JSON.parse(packText).nodes.find((node: { nodeId: string }) => node.nodeId === 'arrival').title).toBe(
    '图形编辑：先认识这个工作日',
  )
  await page.getByRole('tab', { name: '节点视图' }).click()
  await page.getByTestId('node-choice-arrive_begin-target').click()
  await page.getByRole('option', { name: /图形编辑：先认识这个工作日/ }).click()
  await page.getByTestId('apply-node').click()
  await expect(page.getByTestId('graph-diagnostics')).toContainText('循环')
  await page.getByTestId('node-choice-arrive_begin-target').click()
  await page.getByRole('option', { name: /先确认「应该发生什么」/ }).click()
  await page.getByTestId('apply-node').click()
  await expect(page.getByTestId('graph-diagnostics')).toContainText('未发现剧情图结构问题')
  await page.getByRole('button', { name: '自动检查', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('请先保存草稿')
  await page.getByRole('button', { name: '保存草稿', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: '操作已保存并记录审计。' })).toBeVisible()
  await page.reload()
  await page
    .locator('.admin-list button')
    .filter({ hasText: `v${JSON.parse(packText).version} ·` })
    .click()
  await expect(page.getByTestId('node-title')).toHaveValue('图形编辑：先认识这个工作日')
  await page.getByRole('button', { name: '自动检查', exact: true }).click()
  await expect(page.locator('.admin-list button[aria-pressed=true]')).toContainText('auto_checked')
  await page.getByRole('button', { name: '审核通过', exact: true }).click()
  await expect(page.locator('.admin-list button[aria-pressed=true]')).toContainText('approved')
  await page.getByRole('button', { name: '发布新版本', exact: true }).click()
  await expect(page.locator('.admin-list button[aria-pressed=true]')).toContainText('新局入口')
  await expect(page.getByTestId('apply-node')).toBeDisabled()
  await page
    .getByTestId('story-graph-scroll')
    .evaluate((element) => element.scrollIntoView({ block: 'start' }))
  await page.screenshot({ path: 'test-results/screenshots/studio-graph-1440.png' })
  await page.getByTestId('node-title').evaluate((element) => element.scrollIntoView({ block: 'start' }))
  await page.screenshot({ path: 'test-results/screenshots/studio-form-1440.png' })
  await page.setViewportSize({ width: 390, height: 844 })
  await page
    .getByTestId('story-graph-scroll')
    .evaluate((element) => element.scrollIntoView({ block: 'start' }))
  await page.screenshot({ path: 'test-results/screenshots/studio-graph-390.png' })
  await page.getByTestId('node-title').evaluate((element) => element.scrollIntoView({ block: 'start' }))
  await page.screenshot({ path: 'test-results/screenshots/studio-form-390.png' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
  await page.goto('/')
  await page.getByRole('button', { name: '开启第一段职境' }).click()
  await expect(page.locator('.scene-location')).toContainText('图形编辑：先认识这个工作日')
  const unchanged = await (await page.request.get(`/api/sessions/${oldSessionPath.split('/').at(-1)}`)).json()
  expect(unchanged.packVersion).toBe(oldSession.packVersion)
  expect(unchanged.node.title).toBe(oldSession.node.title)
  await page.goto('/admin')
  await page
    .locator('.admin-list button')
    .filter({ hasText: `v${oldSession.packVersion} ·` })
    .click()
  await page.getByRole('button', { name: '回退入口至此版本' }).click()
  await expect(page.locator('.admin-list button[aria-pressed=true]')).toContainText('新局入口')
})
