import { sqliteTable, text, integer, primaryKey, index, real } from 'drizzle-orm/sqlite-core'

export const users = sqliteTable('users', { id: text('id').primaryKey(), username: text('username').unique(), passwordHash: text('password_hash'), isGuest: integer('is_guest', { mode: 'boolean' }).notNull().default(true), createdAt: text('created_at').notNull() })
export const userRoles = sqliteTable('user_roles', { userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }), role: text('role', { enum: ['editor', 'reviewer', 'admin'] }).notNull() }, t => [primaryKey({ columns: [t.userId, t.role] })])
export const authSessions = sqliteTable('auth_sessions', { tokenHash: text('token_hash').primaryKey(), userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }), csrfToken: text('csrf_token').notNull(), expiresAt: integer('expires_at').notNull(), createdAt: text('created_at').notNull() })
export const packs = sqliteTable('packs', { id: text('id').notNull(), version: text('version').notNull(), datasetVersion: text('dataset_version').notNull(), contentBuildId: text('content_build_id').notNull(), assetManifestVersion: text('asset_manifest_version').notNull(), manifest: text('manifest').notNull(), checksum: text('checksum').notNull(), status: text('status').notNull(), domainReviewStatus: text('domain_review_status').notNull(), active: integer('active').notNull(), createdAt: text('created_at').notNull() }, t => [primaryKey({ columns: [t.id, t.version] })])
export const sessions = sqliteTable('sessions', { id: text('id').primaryKey(), ownerId: text('owner_id').notNull().references(() => users.id, { onDelete: 'cascade' }), title: text('title').notNull(), packId: text('pack_id').notNull(), packVersion: text('pack_version').notNull(), currentBranchId: text('current_branch_id').notNull(), createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull() }, t => [index('sessions_owner_idx').on(t.ownerId, t.updatedAt)])
export const branches = sqliteTable('branches', { id: text('id').primaryKey(), sessionId: text('session_id').notNull().references(() => sessions.id, { onDelete: 'cascade' }), parentBranchId: text('parent_branch_id'), forkEventSeq: integer('fork_event_seq').notNull(), revision: integer('revision').notNull(), state: text('state').notNull(), createdAt: text('created_at').notNull() })
export const eventLogs = sqliteTable('event_logs', { id: text('id').primaryKey(), sessionId: text('session_id').notNull().references(() => sessions.id, { onDelete: 'cascade' }), branchId: text('branch_id').notNull().references(() => branches.id, { onDelete: 'cascade' }), eventSeq: integer('event_seq').notNull(), kind: text('kind').notNull(), actor: text('actor').notNull(), channel: text('channel').notNull(), recipientId: text('recipient_id'), payload: text('payload').notNull(), stateAfter: text('state_after').notNull(), createdAt: text('created_at').notNull() })
export const modelCalls = sqliteTable('model_calls', { id: text('id').primaryKey(), turnId: text('turn_id'), provider: text('provider').notNull(), modelVersion: text('model_version').notNull(), promptVersion: text('prompt_version').notNull(), packVersion: text('pack_version').notNull(), factIds: text('fact_ids').notNull(), inputTokens: integer('input_tokens').notNull(), outputTokens: integer('output_tokens').notNull(), latencyMs: integer('latency_ms').notNull(), costEstimate: real('cost_estimate'), costSource: text('cost_source').notNull(), createdAt: text('created_at').notNull() })
